"""
config.py
Loads your settings from the .env file and checks nothing important is missing.
You do not edit this file — it just reads your .env.
"""

import os
import sys
import datetime
import pytz
from dotenv import load_dotenv

load_dotenv()

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
ALLOWED_TELEGRAM_USER_ID = os.getenv("ALLOWED_TELEGRAM_USER_ID", "").strip()
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "").strip()
GOOGLE_SERVICE_ACCOUNT_FILE = os.getenv(
    "GOOGLE_SERVICE_ACCOUNT_FILE", "credentials/google-service-account.json"
).strip()
GOOGLE_SHEET_ID = os.getenv("GOOGLE_SHEET_ID", "").strip()
# For cloud hosting only: paste the whole service-account JSON into this one env
# var so you never upload the key file anywhere public. Local runs use the file.
GOOGLE_CREDENTIALS_JSON = os.getenv("GOOGLE_CREDENTIALS_JSON", "").strip()
DEFAULT_USD_TO_PHP_RATE = float(os.getenv("DEFAULT_USD_TO_PHP_RATE", "58.50"))
TIMEZONE = os.getenv("TIMEZONE", "Asia/Manila").strip()

# The model used to read your messages. Haiku is the cheapest and is great at this.
AI_MODEL = "claude-haiku-4-5-20251001"

# Accounts whose "Account Type" (in the Accounts tab) is one of these are
# treated as NOT spendable: /balance shows them under a separate locked
# section and the AI won't count them as money you can spend. Edit the
# Account Type cell in your sheet to e.g. "savings", "investment" or
# "crypto" to lock an account.
ILLIQUID_ACCOUNT_TYPES = {"savings", "investment", "crypto", "locked", "illiquid"}


def now():
    """
    Current time IN YOUR TIMEZONE (Asia/Manila by default).

    Everything that stamps a date/time must use this instead of
    datetime.now()/date.today(). Railway servers run on UTC, which is 8 hours
    behind Manila — with the naive calls, anything you logged between midnight
    and 8am was recorded under YESTERDAY's date (and /report put the start of
    each month into the previous month).
    """
    return datetime.datetime.now(pytz.timezone(TIMEZONE))


def today_iso():
    """Today's date (YYYY-MM-DD) in your timezone."""
    return now().date().isoformat()


# Names of the tabs in your Google Sheet (must match exactly).
SHEET_TRANSACTIONS = "Transactions"
SHEET_ACCOUNTS = "Accounts"
SHEET_CLIENTS = "Clients"
SHEET_CATEGORIES = "Categories"
SHEET_SUMMARY = "Monthly Summary"
SHEET_SETTINGS = "Settings"
SHEET_AUDIT = "Audit Log"


def check():
    """Stop early with a friendly message if a required value is missing."""
    missing = []
    if not TELEGRAM_BOT_TOKEN or "PASTE" in TELEGRAM_BOT_TOKEN:
        missing.append("TELEGRAM_BOT_TOKEN")
    if not ALLOWED_TELEGRAM_USER_ID or "PASTE" in ALLOWED_TELEGRAM_USER_ID:
        missing.append("ALLOWED_TELEGRAM_USER_ID")
    if not ANTHROPIC_API_KEY or "PASTE" in ANTHROPIC_API_KEY:
        missing.append("ANTHROPIC_API_KEY")
    if not GOOGLE_SHEET_ID or "PASTE" in GOOGLE_SHEET_ID:
        missing.append("GOOGLE_SHEET_ID")
    if not os.path.exists(GOOGLE_SERVICE_ACCOUNT_FILE) and not GOOGLE_CREDENTIALS_JSON:
        missing.append("Google credentials (the JSON file in credentials/, or "
                       "GOOGLE_CREDENTIALS_JSON if you're hosting)")

    if missing:
        print("\n  Setup not finished yet. These are still missing from your .env:")
        for m in missing:
            print(f"   - {m}")
        print("\n  Open your .env file, fill those in, then run the bot again.\n")
        sys.exit(1)
